### PR TITLE
Fixing bug when system-generated tags are blocked

### PR DESCRIPTION
**Pull request by mrosendin**
:neckbeard: 

Fixes a bug that was encountered when a tag is applied via a custom field dropdown with the tag option enabled on ticket submission. See issue #6. Prior to the fix, Tag Locker wouldn't accept the system-generated tag because it was neither restricted (on the ticket prior to ticket creation or app install) nor allowable (in the app settings).

cc @maximeprades @Eshen @epritchard @ckumar1 @jstjoe 

__Summary of changes__:
* Recalculating restricted tags prior to validating tags and building the interface on tagsChanged()
* Called onTagsChanged() directly after tags are added and removed

## Screenshot
screen shot 2015-12-04 at 4

## Reference
* [Ticket #1322563](https://support.zendesk.com/agent/tickets/1322563)
* Issue #6 

## Risks
* Low

### CODE REVIEW

**Comment by maximeprades** [comment]
@jstjoe any chance you're able to review this?

**Comment by jeremiahcurrier** [comment]
:+1:

**Comment by jstjoe** [comment]
a couple notes:
- I think it is overkill to run the whole initialize function whenever tags are changed. Would be better to break out the logic that needs to be run when tags are changed and keep the rest in a separate initialize function.
- please bump the version number to reflect the update. otherwise I haven't tested but looks good.

**Comment by mrosendin** [comment]
Hey @jstjoe took your comments into account. Could you take one last look before I merge? Thanks.

**Comment by maximeprades** [comment]
:+1:

**Pull request merged**
